<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.instanto</groupId>
    <artifactId>teavm-compat</artifactId>
    <version>0.1.0-SNAPSHOT</version>
  </parent>
  <artifactId>jsinterop-base-compat</artifactId>
  <dependencies>
    <dependency>
      <groupId>org.teavm</groupId>
      <artifactId>teavm-jso</artifactId>
      <version>${teavm.version}</version>
    </dependency>
  </dependencies>
  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
      </resource>
      <resource>
        <directory>..</directory>
        <targetPath>META-INF</targetPath>
        <includes>
          <include>LICENSE</include>
          <include>NOTICE</include>
          <include>upstream/provenance.json</include>
          <include>upstream/bindings-lock.json</include>
        </includes>
      </resource>
    </resources>
  </build>
</project>
