<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>io.instanto</groupId>
    <artifactId>teavm-compat</artifactId>
    <version>0.1.0-SNAPSHOT</version>
  </parent>
  <artifactId>jsinterop-binding-generator</artifactId>
  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.13.2</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>com.github.javaparser</groupId>
      <artifactId>javaparser-core</artifactId>
      <version>3.28.2</version>
    </dependency>
    <dependency>
      <groupId>com.google.elemental2</groupId>
      <artifactId>elemental2-core</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.google.elemental2</groupId>
      <artifactId>elemental2-dom</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.google.elemental2</groupId>
      <artifactId>elemental2-promise</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.google.elemental2</groupId>
      <artifactId>elemental2-svg</artifactId>
      <scope>provided</scope>
    </dependency>
    <dependency>
      <groupId>com.google.elemental2</groupId>
      <artifactId>elemental2-webstorage</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>
  <build>
    <resources>
      <resource>
        <directory>src/main/resources</directory>
      </resource>
      <resource>
        <directory>..</directory>
        <targetPath>META-INF</targetPath>
          <includes>
            <include>LICENSE</include>
            <include>NOTICE</include>
          </includes>
      </resource>
    </resources>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.9.0</version>
        <executions>
          <execution>
            <id>locate-binding-inputs</id>
            <phase>initialize</phase>
            <goals>
              <goal>properties</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
      <plugin>
        <groupId>org.codehaus.mojo</groupId>
        <artifactId>exec-maven-plugin</artifactId>
        <version>3.6.3</version>
        <executions>
          <execution>
            <phase>process-classes</phase>
            <goals>
              <goal>java</goal>
            </goals>
            <configuration>
              <mainClass>io.instanto.compat.GenerateBindings</mainClass>
              <arguments>
                <argument>${project.basedir}/../target/compat/elemental2</argument>
                <argument>${com.google.elemental2:elemental2-core:jar}</argument>
                <argument>${com.google.elemental2:elemental2-dom:jar}</argument>
                <argument>${com.google.elemental2:elemental2-promise:jar}</argument>
                <argument>${com.google.elemental2:elemental2-svg:jar}</argument>
                <argument>${com.google.elemental2:elemental2-webstorage:jar}</argument>
              </arguments>
            </configuration>
            <id>elemental2-bindings</id>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
