<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.instanto</groupId>
    <artifactId>instanto-org-pom</artifactId>
    <version>0.1.0-SNAPSHOT</version>
    <relativePath/>
  </parent>
  <artifactId>teavm-compat-bom</artifactId>
  <packaging>pom</packaging>
  <dependencyManagement>
    <dependencies><dependency><groupId>io.instanto</groupId><artifactId>teavm-classlib-compat</artifactId><version>${project.version}</version></dependency><dependency><groupId>io.instanto</groupId><artifactId>gwt-uibinder-processor</artifactId><version>${project.version}</version></dependency>
      <dependency>
        <groupId>io.instanto</groupId>
        <artifactId>jsinterop-binding-generator</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.instanto</groupId>
        <artifactId>jsinterop-base-compat</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.instanto</groupId>
        <artifactId>elemental2-compat</artifactId>
        <version>1.2.3-SNAPSHOT</version>
      </dependency>
      <dependency>
        <groupId>io.instanto</groupId>
        <artifactId>gwt-modular-services-compat</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.instanto</groupId>
        <artifactId>gwt-user-compat</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.instanto</groupId>
        <artifactId>gwt-api</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <groupId>io.instanto</groupId>
  <version>0.1.0-SNAPSHOT</version>

</project>
