<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <artifactId>teavm-compat-bom</artifactId>
  <packaging>pom</packaging>
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.instanto</groupId>
        <artifactId>jsinterop-binding-generator</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.instanto</groupId>
        <artifactId>jsinterop-base-compat</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.instanto</groupId>
        <artifactId>elemental2-compat</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.instanto</groupId>
        <artifactId>gwt-modular-services-compat</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.instanto</groupId>
        <artifactId>gwt-user-compat</artifactId>
        <version>${project.version}</version>
      </dependency>
      <dependency>
        <groupId>io.instanto</groupId>
        <artifactId>gwt-api-contracts</artifactId>
        <version>${project.version}</version>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <groupId>io.instanto</groupId>
  <version>0.1.0-SNAPSHOT</version>
  <distributionManagement>
    <repository>
      <id>github</id>
      <url>https://maven.pkg.github.com/instanto-io/teavm-compat</url>
    </repository>
  </distributionManagement>
</project>
